services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: payroll
      MYSQL_USER: nobita
      MYSQL_PASSWORD: COK@ScOTNbK9
    ports:
      - "3306:3306"
    volumes: 
      - ./mysqldata:/var/lib/mysql
    networks:
      - talenavi
  payroll:
    container_name: payroll-service
    build:  
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    command: sh -c "npm run migrate && npm start"
    ports:
      - "9000:9000"
    networks:
      - talenavi
networks:
  talenavi:
    external: true